PLUGINOBJECTS = ChannelMath.o PluginRegistration.o
PLUGINNAME = ChannelMath
RESOURCES = com.casanico.ChannelMath.png com.casanico.ChannelMath.svg

TOP_SRCDIR = ../..
include $(TOP_SRCDIR)/Makefile.master

