PLUGINOBJECTS = \
ChannelMath.o

PLUGINNAME = Community

TOP_SRCDIR = ..

RESOURCES = \
$(TOP_SRCDIR)/Color/ChannelMath/com.casanico.ChannelMath.png \
$(TOP_SRCDIR)/Color/ChannelMath/com.casanico.ChannelMath.svg

VPATH += \
$(TOP_SRCDIR)/Color/ChannelMath

include $(TOP_SRCDIR)/Makefile.master

CXXFLAGS += \
-I. \
-I$(TOP_SRCDIR)/Color/ChannelMath

